# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://greys.github.io/
baseurl: /
title: Gleb Reys
author: Gleb Reys
description: Personal blog and resume
avatar: gleb-reys.jpg
email: gleb@reys.net
github: greys # username
twitter: glebreys
linkedin: greys
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: GlebReys
google_analytics: UA-88087-32

# needed for travis-ci build
exclude: [vendor]
